name: Convert PNG to JPG

on:
  push:
    paths:
      - '**.png'

jobs:
  convert-images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install ImageMagick
        run: sudo apt-get update && sudo apt-get install -y imagemagick

      - name: Convert PNG to JPG
        run: |
          for img in $(find . -name "*.png"); do
            new_img="${img%.png}.jpg"
            convert "$img" "$new_img"
          done

      - name: Commit converted JPGs
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Convert PNGs to JPGs" || echo "No changes to commit"
          git push
