name: Convert PNG to JPG

on:
  push:
    paths:
      - '**.png'

jobs:
  convert-images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install ImageMagick
        run: sudo apt-get update && sudo apt-get install -y imagemagick

      - name: Convert PNG to JPG and delete PNGs
        run: |
          find . -type f -name "*.png" -print0 | while IFS= read -r -d '' img; do
            new_img="${img%.png}.jpg"
            convert "$img" "$new_img" && rm "$img"
          done

      - name: Commit converted JPGs
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
          git add .
          git commit -m "Convert PNGs to JPGs" || echo "No changes to commit"
          git push
